						<ul>
							<table border="0" cellpadding="0" cellspacing="0">
								<tr>
									<td>
										<a href="/index.html" onmouseover="setOverImg('1','');" onmouseout="setOutImg('1','');" target=""><img src="/img/buttons/button1up.png" border="0" id="button1" vspace="1" hspace="1"></a>
										<a href="/experience/index.html" onmouseover="setOverImg('3','');" onmouseout="setOutImg('3','');" target=""><img src="/img/buttons/button3up.png" border="0" id="button3" vspace="1" hspace="1"></a>
										<a href="/aboutme/index.html" onmouseover="setOverImg('4','');" onmouseout="setOutImg('4','');" target=""><img src="/img/buttons/button4up.png" border="0" id="button4" vspace="1" hspace="1"></a>
										<a href="/gallery/index.html" onmouseover="setOverImg('5','');" onmouseout="setOutImg('5','');" target=""><img src="/img/buttons/button5up.png" border="0" id="button5" vspace="1" hspace="1"></a>
										<a href="/contact/index.html" onmouseover="setOverImg('6','');" onmouseout="setOutImg('6','');" target=""><img src="/img/buttons/button6up.png" border="0" id="button6" vspace="1" hspace="1"></a>
									</td>
								</tr>
							</table>
						</ul>