			<aside id="sidebar">
				
					<script type="text/javascript" src="/javascript/sidebar.js"></script>
					<script type="text/javascript" src="/javascript/mootools.js"></script>	
					
					<h2>Social Media</h2>
					<a href="/"><img src="/img/home.png" width="40" height="40" /></a></li>
					<a href="https://www.facebook.com/Rafase282" target="_blank"><img src="/img/Find-Me-On-Facebook.png" width="40" height="40" /></a>
					<a href="http://twitter.com/rafase282" target="_blank"><img src="/img/find_me_on_twitter.png" width="40" height="40" /></a>
					<a href="https://plus.google.com/u/0/115236669989951776897/posts" target="_blank"><img src="/img/g+.png" width="40" height"40" /></a>						
					
					<p>This website is best viewed by 
						<a href="http://www.google.com/chrome/index.html" target="_blank"><img src="/img/chromium-logo.png" width="40" height="40"/></a>
						<a href="http://www.opera.com/download/" target="_blank"><img src="/img/opera.png" width="40" height="40"/></a>
						<a href="http://www.mozilla.org/en-US/firefox/new/" target="_blank"><img src="/img/firefox.png" width="40" height="40"/></a>
						<a href="http://www.maxthon.com/" target="_blank"><img src="/img/maxthon.png" width="40" height="40"/></a>
					</p>	
								
			</aside>